-- =============================================================
-- 1. TABLES (order respects FK dependencies)
-- =============================================================

-- Social Media Plans: holds the plan-level metadata for a
-- 15-day or 30-day content calendar generated by the tool.
CREATE TABLE IF NOT EXISTS public.social_media_plans_algoritmo_milionario (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id         UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  title           TEXT NOT NULL,
  product_name    TEXT NOT NULL,
  offer_info      TEXT,
  target_audience TEXT,
  differentials   TEXT,
  duration_days   INT NOT NULL CHECK (duration_days IN (15, 30)),
  start_date      DATE NOT NULL,
  status          TEXT DEFAULT 'draft' CHECK (status IN ('draft','active','completed')),
  created_at      TIMESTAMPTZ DEFAULT NOW(),
  updated_at      TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_social_plans_user_created
  ON public.social_media_plans_algoritmo_milionario(user_id, created_at DESC);

-- Social Media Plan Items: one row per piece of content within a plan.
-- Stories can have slot_number 1-3; other content types always use slot 1.
CREATE TABLE IF NOT EXISTS public.social_media_plan_items_algoritmo_milionario (
  id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  plan_id        UUID NOT NULL REFERENCES public.social_media_plans_algoritmo_milionario(id) ON DELETE CASCADE,
  day_number     INT NOT NULL,              -- 1 to 30
  scheduled_date DATE,                      -- computed from plan start_date + day_number
  content_type   TEXT NOT NULL CHECK (content_type IN ('reel','feed','carousel','story')),
  slot_number    INT NOT NULL DEFAULT 1,    -- stories: 1-3; posts: always 1
  title          TEXT NOT NULL,
  content        TEXT NOT NULL,             -- copy/script of the content
  caption        TEXT,                      -- caption + hashtags
  status         TEXT DEFAULT 'pending' CHECK (status IN ('pending','done','skipped')),
  created_at     TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_social_plan_items_plan
  ON public.social_media_plan_items_algoritmo_milionario(plan_id);

CREATE INDEX IF NOT EXISTS idx_social_plan_items_user_via_plan
  ON public.social_media_plan_items_algoritmo_milionario(plan_id, day_number ASC);

-- Products: stores the full AI-generated product analysis output including
-- headlines, VSL/TSL structures, order bumps, and funnel offers.
CREATE TABLE IF NOT EXISTS public.products_algoritmo_milionario (
  id                       UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id                  UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  raw_description          TEXT,
  market                   TEXT,
  price                    NUMERIC(10,2),
  icp                      TEXT,
  differentials            TEXT,
  product_name             TEXT,
  headlines                JSONB,    -- array of 4 headline strings
  description              TEXT,
  unique_mechanism         JSONB,    -- { problem_mechanism: TEXT, solution_mechanism: TEXT }
  social_proof_suggestions JSONB,   -- array of suggestion strings
  vsl_structure            JSONB,   -- array of { section, objective, key_points[] }
  tsl_structure            JSONB,   -- same structure as vsl_structure but for Text Sales Letter
  order_bump               JSONB,   -- { name, description, price_suggestion, why }
  upsell                   JSONB,   -- { name, description, price_suggestion, positioning }
  downsell                 JSONB,   -- { name, description, price_suggestion, positioning }
  status                   TEXT DEFAULT 'draft' CHECK (status IN ('draft','generated','saved')),
  created_at               TIMESTAMPTZ DEFAULT NOW(),
  updated_at               TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_products_user_created
  ON public.products_algoritmo_milionario(user_id, created_at DESC);

-- Offer Analyses: stores the structured output from the offer analyser tool,
-- including per-dimension scores and prioritised improvement suggestions.
CREATE TABLE IF NOT EXISTS public.offer_analyses_algoritmo_milionario (
  id                    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id               UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  source_url            TEXT,
  source_text           TEXT NOT NULL,
  analysis              JSONB,   -- full structured analysis
  scores                JSONB,   -- scores per dimension
  modeling_suggestions  JSONB,   -- prioritized improvement suggestions
  created_at            TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_offer_analyses_user_created
  ON public.offer_analyses_algoritmo_milionario(user_id, created_at DESC);

-- =============================================================
-- 2. ROW LEVEL SECURITY
-- =============================================================

ALTER TABLE public.social_media_plans_algoritmo_milionario      ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.social_media_plan_items_algoritmo_milionario ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products_algoritmo_milionario                ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.offer_analyses_algoritmo_milionario          ENABLE ROW LEVEL SECURITY;

-- Policies via DO block (CREATE POLICY IF NOT EXISTS not supported before PG17)
DO $$ BEGIN

  -- social_media_plans
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename='social_media_plans_algoritmo_milionario' AND policyname='social_plans: usuário acessa os próprios') THEN
    CREATE POLICY "social_plans: usuário acessa os próprios"
      ON public.social_media_plans_algoritmo_milionario FOR ALL
      USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename='social_media_plans_algoritmo_milionario' AND policyname='social_plans: service_role gerencia') THEN
    CREATE POLICY "social_plans: service_role gerencia"
      ON public.social_media_plans_algoritmo_milionario FOR ALL
      USING (auth.role() = 'service_role');
  END IF;

  -- social_media_plan_items
  -- Items are secured through their parent plan's user_id via a subquery.
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename='social_media_plan_items_algoritmo_milionario' AND policyname='social_plan_items: usuário acessa os próprios') THEN
    CREATE POLICY "social_plan_items: usuário acessa os próprios"
      ON public.social_media_plan_items_algoritmo_milionario FOR ALL
      USING (
        EXISTS (
          SELECT 1
          FROM public.social_media_plans_algoritmo_milionario p
          WHERE p.id = plan_id
            AND p.user_id = auth.uid()
        )
      )
      WITH CHECK (
        EXISTS (
          SELECT 1
          FROM public.social_media_plans_algoritmo_milionario p
          WHERE p.id = plan_id
            AND p.user_id = auth.uid()
        )
      );
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename='social_media_plan_items_algoritmo_milionario' AND policyname='social_plan_items: service_role gerencia') THEN
    CREATE POLICY "social_plan_items: service_role gerencia"
      ON public.social_media_plan_items_algoritmo_milionario FOR ALL
      USING (auth.role() = 'service_role');
  END IF;

  -- products
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename='products_algoritmo_milionario' AND policyname='products: usuário acessa os próprios') THEN
    CREATE POLICY "products: usuário acessa os próprios"
      ON public.products_algoritmo_milionario FOR ALL
      USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename='products_algoritmo_milionario' AND policyname='products: service_role gerencia') THEN
    CREATE POLICY "products: service_role gerencia"
      ON public.products_algoritmo_milionario FOR ALL
      USING (auth.role() = 'service_role');
  END IF;

  -- offer_analyses
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename='offer_analyses_algoritmo_milionario' AND policyname='offer_analyses: usuário acessa as próprias') THEN
    CREATE POLICY "offer_analyses: usuário acessa as próprias"
      ON public.offer_analyses_algoritmo_milionario FOR ALL
      USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename='offer_analyses_algoritmo_milionario' AND policyname='offer_analyses: service_role gerencia') THEN
    CREATE POLICY "offer_analyses: service_role gerencia"
      ON public.offer_analyses_algoritmo_milionario FOR ALL
      USING (auth.role() = 'service_role');
  END IF;

END $$;
